easy_admin:
    entities:
        User:
            class: App\Entity\User
        Subscription:
            class: App\Entity\Subscription
            list:
                fields:
                    - id
                    - task
                    - user
                    - status
                    - { property: 'image', type: 'image', base_path: '/' }
        QrCode:
            class: App\Entity\QrCode
        Task:
            class: App\Entity\Task

    user:
        name_property_path: 'username'
