app.game.home:
    path: /
    controller: App\Controller\GameController::index

app.game.camera:
    path: /camera
    controller: App\Controller\GameController::camera

app.game.tasks:
    path: /tasks
    controller: App\Controller\GameController::tasks

app.game.rewards:
    path: /rewards
    controller: App\Controller\GameController::rewards

app.game.events:
    path: /events
    controller: App\Controller\GameController::events

app.game.rules:
    path: /rules
    controller: App\Controller\GameController::rules

app.game.leaderboard:
    path: /leaderboard
    controller: App\Controller\GameController::leaderboard

# post calls

app.game.validate_qr:
    path: /validate-qr
    controller: App\Controller\GameController::postQrCode



# authentication

app.user.login:
    path: /facebookResponse
    controller: App\Controller\UserController::loginResponse

app.user.logout:
    path: /logout
